# image will be published to ghcr.io/<user>/<name>
name: qwerty
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      #- https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/ryanabx-cosmic-epoch-%OS_VERSION%.repo
    install:
      - darktable      
      - gnome-boxes
      - libreoffice
      - ulauncher
      - nextcloud-client
      - alacritty
      - qt5ct
      - libX11
      - libXft
      - libXinerama
      - freetype
      - fontconfig
      - libxcb
      - make
      - git
      - imlib2
      - xset
      - xorg-x11-server-Xorg
      - dunst
      - picom
      - feh
      - flameshot
      - rofi
      - dbus-x11
      - xorg-x11-drv-amdgpu
      - Thunar
      - engrampa
      - thunar-volman
      - thunar-archive-plugin
      - thunar-vcs-plugin
      - thunar-media-tags-plugin
      - tumbler
      - lxappearance 
      - lxpolkit
      - pavucontrol
      - xsetroot
      - libX11-devel
      - libXft-devel
      - libXinerama-devel
      - libxcb-devel
      - imlib2-devel
      - qt5ct
      - qt6ct
      - plasma-breeze
      - breeze-gtk
      - adwaita-qt5
      - adwaita-qt6
      - cosmic-desktop
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.discordapp.Discord
        - com.dec05eba.gpu_screen_recorder
        - com.obsproject.Studio
        - com.obsproject.Studio.Plugin.GStreamerVaapi
        - com.obsproject.Studio.Plugin.Gstreamer
        - com.obsproject.Studio.Plugin.OBSVkCapture
        - com.spotify.Client
        - fr.handbrake.ghb
        - org.gimp.GIMP
        - org.gimp.GIMP.Plugin.FocusBlur
        - org.gimp.GIMP.Plugin.Lensfun
        - org.gimp.GIMP.Plugin.Resynthesizer
        - org.supertuxproject.SuperTux
        - org.freedesktop.Platform.VulkanLayer.MangoHud
        - com.valvesoftware.Steam
        - com.github.tchx84.Flatseal
        - io.github.dosbox-staging
        - md.obsidian.Obsidian
        - net.lutris.Lutris
        - com.makemkv.MakeMKV
        - net.scribus.Scribus
        - org.kde.kdenlive
        - org.kde.okular
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog
      
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
